// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11Pj8naS2A0s5E8aWyomMSptXBTyPswA',
    appId: '1:532132399001:android:c1f987e1192f373d44f508',
    messagingSenderId: '532132399001',
    projectId: 'hiddentable-ec165',
    storageBucket: 'hiddentable-ec165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtu-20IQ8sO6uRNQSWhWywtbpaB5S_Jkw',
    appId: '1:532132399001:ios:0fd7f95ad0e0243644f508',
    messagingSenderId: '532132399001',
    projectId: 'hiddentable-ec165',
    storageBucket: 'hiddentable-ec165.appspot.com',
    androidClientId:
        '532132399001-0pgmtbsfafqj0rgkt9oihcsdm0k53e98.apps.googleusercontent.com',
    iosClientId:
        '532132399001-jq4ptrf7b5f7gd4gjdhqllqcn6hgp3fg.apps.googleusercontent.com',
    iosBundleId: 'com.hiddentable.de',
  );
}
